Homework 3
t-shaghoyan/ta-academy_3 pull request #3
Opened 2023-10-26 14:20 UTC by t-shaghoyan

2023-10-26 18:12 UTC, valeriyazin requested changes

2023-10-26 18:12 UTC, valeriyazin commented on manual/lesson_3/homework_3/Homework3.postman_collection.json
> +					"raw": "https://uvp-0000-uhc-desktop.gusadev.com/ms/customer/registration ",
invalid url (extra white space)

2023-10-26 18:12 UTC, valeriyazin commented on manual/lesson_2/homework_2/Home-2-Tigran.md
why do you add 2nd homework to this branch?

2023-10-27 08:59 UTC, t-shaghoyan commented on manual/lesson_2/homework_2/Home-2-Tigran.md
my apologies, it's already fixed, thanks for your attention

2023-11-15 10:59 UTC, merged